version: '3.3'

services:
    wanderluster:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - redis
            - mysql
        ports:
            - "80:8080"
        links:
            - redis:redis
            - mysql:mysql
        volumes:
            - ./:/var/www/html
        environment:
            APP_DEBUG: 0
            APP_ENV: local
    redis:
        image: redis
        ports:
        - "6379:6379"
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: wanderluster_api
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: wanderluster